name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create server file archives
        run: |
          find . -name Init.con -execdir zip -r server.zip . -x .* \;
      - name: Create release archive
        run: |
          zip -r bf2-modded-maps-${{ github.ref_name }}.zip . -i *.md *.zip
      - name: Create hash files
        run: |
          md5sum bf2-modded-maps-${{ github.ref_name }}.zip | cut -d" " -f1 > bf2-modded-maps-${{ github.ref_name }}.zip.md5
          sha256sum bf2-modded-maps-${{ github.ref_name }}.zip | cut -d" " -f1 > bf2-modded-maps-${{ github.ref_name }}.zip.sha256
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: bf2-modded-maps-${{ github.ref_name }}.zip*
          draft: true
          generate_release_notes: true
          name: bf2-modded-maps ${{ github.ref_name }}
          body: This is the ${{ github.ref_name }} release of bf2-modded-maps.

